baseURL = "https://harsha-blog.netlify.app/"
languageCode = "en-us"
title = "My blog"
theme = "hugo-ink"
paginate = 5

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	subtitle = "A place to log my thoughts with emphasis on programming"

	# Optional 64x64 avatar image.
	avatar = "https://image.freepik.com/free-vector/fantastic-background-funny-burger-character_23-2147629952.jpg?1"

	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/Harsha-vardhan30"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"