[build]
	publish = "public"
	command = "hugo --gc --minify"

[build.environment]
	HUGO_VERSION = "0.70.0"
  	HUGO_THEME = "hugo-ink"
	HUGO_BASEURL = "/"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404