[build]
	publish = "public"
	command = "env REV_EMAIL=${REV_EMAIL} hugo --gc --minify"

[build.environment]
	HUGO_VERSION = "0.119.0"
  	HUGO_THEME = "hugo-ink"
	HUGO_BASEURL = "/"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404